合并变量

output_data/LAD_landuse_group_stats_wide.csv
output_data/LAD_free_POI_group_with_9_category_summary_wide.csv
output_data/merged_census_data.csv
output_data/cleaned_crime_total_sum.csv
output_data/cleaned_crime_asb_sum.csv


在excel整理后的因变量：Detailed_LA_20222023_A1.csv


最终合并成output_data/final_merged.csv，

此版本包含一些无关变量，以及很多空字段，将字段名称进行整理，删除无关变量和空字段的版本见output_data/final_merged_cleaned.csv

此csv后续保存在了"Homelessness_England/analysis/final_merged_cleaned.csv",二者一致。

In [1]:
import pandas as pd

# 读取文件
df_landuse = pd.read_csv('output_data/LAD_landuse_group_stats_wide.csv')
df_socio = pd.read_csv('output_data/merged_census_data.csv')
df_poi = pd.read_csv('output_data/LAD_free_POI_group_with_9_category_summary_wide.csv')

# 统一主键字段名
df_socio = df_socio.rename(columns={'geography code': 'LAD21CD'})

# 合并
df_merged = df_landuse.merge(df_socio, on='LAD21CD').merge(df_poi, on='LAD21CD')

# 查看结果
print(df_merged.head())

#df_merged.to_csv('merged_output_01.csv', index=False)

     LAD21CD             LAD21NM_x  Agricultural_and_Rural  \
0  E06000001            Hartlepool                0.574073
1  E06000002         Middlesbrough                0.282225
2  E06000003  Redcar and Cleveland                0.092392
3  E06000004      Stockton-on-Tees                0.591487
4  E06000005            Darlington                0.764422

   Natural_Ecological_and_Public  Residential_and_Commercial  \
0                       0.174667                    0.251260
1                       0.125426                    0.592349
2                       0.627864                    0.279744
3                       0.157774                    0.250739
4                       0.072609                    0.162969

   Household composition: Total; measures: Value  \
0                                        40930.0
1                                        60261.0
2                                        61640.0
3                                        83756.0
4                                        48915.0

   Household composition: One person household; measures: Value  \
0                                            13616.0
1                                            19964.0
2                                            20663.0
3                                            25980.0
4                                            16714.0

   Household composition: One person household: Aged 66 years and over; measures: Value  \
0                                             5647.0
1                                             7739.0
2                                             9739.0
3                                            10812.0
4                                             6851.0

   Household composition: One person household: Other; measures: Value  \
0                                             7969.0
1                                            12225.0
2                                            10924.0
3                                            15168.0
4                                             9863.0

   Household composition: Single family household; measures: Value  ...  \
0                                            25845.0                ...
1                                            36756.0                ...
2                                            39003.0                ...
3                                            54449.0                ...
4                                            30395.0                ...

              LAD21NM_y  Accommodation_and_Food  Arts_and_Recreation  \
0            Hartlepool                   182.0                 58.0
1         Middlesbrough                   104.0                 63.0
2  Redcar and Cleveland                   126.0                123.0
3      Stockton-on-Tees                   199.0                112.0
4            Darlington                   267.0                 58.0

   Financial_Institutions  Healthcare_Centers  Information_and_Communication  \
0                    37.0                32.0                          248.0
1                    22.0                32.0                           99.0
2                    28.0                26.0                          204.0
3                    25.0                43.0                          166.0
4                    21.0                39.0                          200.0

   Other  Personal_and_Household_Svcs  Retail  Transportation_Facilities
0  429.0                         48.0   129.0                        1.0
1   92.0                         18.0   139.0                        8.0
2  392.0                         23.0   103.0                        1.0
3  348.0                         47.0   195.0                        6.0
4  305.0                        138.0   225.0                        9.0

[5 rows x 82 columns]

In [ ]:
#合并因变量

# 读取已合并的主表
df_main = df_merged

# 读取详细表
df_detail = pd.read_csv('Detailed_LA_20222023_A1.csv')

# 检查详细表主键字段名（假设为"LAD21CD"，如有不同请替换）
# 例如，如果是 'code'，则用 df_detail.rename(columns={'code': 'LAD21CD'}, inplace=True)

# 合并
df_homeless = df_main.merge(df_detail, on='LAD21CD', how='left')

In [4]:
#合并crime数据

# 读取主表
df_main2 = df_homeless

# 读取犯罪数据
df_asb = pd.read_csv('output_data/cleaned_crime_asb_sum.csv')
df_total = pd.read_csv('output_data/cleaned_crime_total_sum.csv')

# 重命名主键字段
df_asb = df_asb.rename(columns={'Local Authority code': 'LAD21CD'})
df_total = df_total.rename(columns={'Local Authority code': 'LAD21CD'})

# 合并ASB犯罪数据
df_merge1 = df_main2.merge(df_asb, on='LAD21CD', how='left')

# 合并总犯罪数据
df_final = df_merge1.merge(df_total, on='LAD21CD', how='left')

# 保存结果
df_final.to_csv('output_data/final_merged.csv', index=False)